#spring:
#  data:
#    redis:
#      host: localhost
#      port: 6379
#  application:
#      name: master-spring-boot
#logging:
#  level:
#    root: info
#management:
#      endpoint:
#        shutdown:
#          enabled: true

spring:
  data:
    redis:
      host: localhost
      port: 6379
  application:
    name: practica1
logging:
  level:
    root: INFO
  file:
    name: logs/practica1.log
management:
  endpoints:
    enabled-by-default: false
    web:
      exposure:
        include: health, info, beans, threaddump, mappings, prometheus
  endpoint:
    info:
      enabled: true
    health:
      show-details: always
      show-components: always
      enabled: true
    beans:
      enabled: true
    threaddump:
      enabled: true
    mappings:
      enabled: true
    prometheus:
      enabled: true